<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\KJ.Domain\KJ.Domain.csproj" />
    <ProjectReference Include="..\KJ.Drivers.Abstractions\KJ.Drivers.Abstractions.csproj" />
    <ProjectReference Include="..\KJ.Diagnostics\KJ.Diagnostics.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NModbus" Version="3.0.83" />
    <PackageReference Include="NModbus.Serial" Version="3.0.83" />
    <PackageReference Include="Polly" Version="8.6.6" />
    <PackageReference Include="System.IO.Ports" Version="8.*" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
