<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
        <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>

        <!-- WinUI 3 -->
        <UseWinUI>true</UseWinUI>
        <EnableMsixTooling>true</EnableMsixTooling>

        <!-- Project Options -->
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>KJ.Modules.Auth</RootNamespace>

        <!-- App Options -->
        <UseRidGraph>true</UseRidGraph>
        <RuntimeIdentifiers Condition="$([MSBuild]::GetTargetFrameworkVersion('$(TargetFramework)')) &gt;= 8">win-x86;win-x64;win-arm64</RuntimeIdentifiers>
        <RuntimeIdentifiers Condition="$([MSBuild]::GetTargetFrameworkVersion('$(TargetFramework)')) &lt; 8">win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="KJ.Modules.Auth.slnx" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.*" />
        <PackageReference Include="Microsoft.Web.WebView2" Version="1.*" />
        <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.*" />
        <PackageReference Include="Prism.Uno.WinUI" Version="9.0.537" />
    </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KJ.Modules.Core\KJ.Modules.Core.csproj" />
    <ProjectReference Include="..\KJ.Infrastructure\KJ.Infrastructure.csproj" />
  </ItemGroup>
</Project>
